### ISSUE TITLE
Port to Minecraft 1.20.1

### ISSUE THREAD

**Issue by Gegy** [LoveTropics/LoveAccessibility#1]

**Comment by sekwah41** [comment]
Ohai

**Comment by sekwah41** [comment]
I've ported it and added a fallback to the native voice if its not enabled.

I've also made it work with the different sides of a sign.

https://github.com/LoveTropics/LoveAccessibility/assets/3209834/2ae7cef6-f3cb-4520-873a-fa56d09d750c

**Comment by sekwah41** [comment]
Though I don't know if it's my system or what but it seems to have a lot of lag with the native narrator

https://github.com/LoveTropics/LoveAccessibility/assets/3209834/3c065f84-9b58-44d2-9f1e-033f5bbcfa6b

**Comment by sekwah41** [comment]
Need write access to the repo so that I don't have to merge https://github.com/sekwah41/LoveAccessibility/tree/1.20.1 to the 1.20.1 branch.

Initially I wanted to check if the libraries loaded though it was easier to check the NVDA\\nvda.exe folder to add a nice little prompt in case people have closed or forgot to enable NVDA.

If a lot of people are using the native narrator, I may look to raise an issue to thread the interactions with the narrator as it causes lag when switching its narration.

**Comment by sekwah41** [comment]
Available on https://github.com/LoveTropics/LoveAccessibility/tree/1.20.1 now

See comparison https://github.com/LoveTropics/LoveAccessibility/compare/1.18...1.20.1

**Comment by sekwah41** [comment]
Note from Gegy, SignText.LINES is the new constant value
